name: run-demo-api-automation-test
run-name: ${{ github.actor }} is running automation api test with Python Behave
on:
  push:
    branches: [ main ]
jobs:
  runAutomatedScript:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - run: sed -i -e 's/username_holder/${{ secrets.APIUSERNAME }}/g' features/.env
      - run: sed -i -e 's/pwd_holder/${{ secrets.APIPWD }}/g' features/.env
      - name: running the behave script
        working-directory:
          document-api/
        run: |
          behave
