name: run-api-automation-test-demo
run-name: ${{ github.actor }} is running demo automation api test with Python Behave
on:
  push:
    branches: [ main ]
jobs:
  runDemoAutomatedScript:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
    matrix:
      os: [ubuntu-latest]
      python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
    	with:
      	  python-version: ${{ matrix.python-version }}
      - name: Install dependencies
    	run: |
      	  python -m pip install --upgrade pip
      	  pip3 install -r requirements.txt
      - run: sed -i -e 's/username_holder/${{ secrets.NEWLISCLIENTID }}/g' /features/.env
      - run: sed -i -e 's/pwd_holder/${{ secrets.NEWLISSECRET }}/g' /features/.env
      - name: running the behave script
    	working-directory:
      	  features/
    	run: |
      	  behave
